# Generated by Django 5.1 on 2024-08-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=49, null=True)),
            ],
            options={
                "db_table": "banks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "ifsc",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("branch", models.CharField(blank=True, max_length=74, null=True)),
                ("address", models.CharField(blank=True, max_length=195, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=26, null=True)),
            ],
            options={
                "db_table": "branches",
                "managed": False,
            },
        ),
    ]
